--- #YAML:1.0
name:               XML-RSS-PicLens
version:            0.03
abstract:           Create a PicLens compatible RSS feed
author:
    - Andy Armstrong <andy.armstrong@messagesystems.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Section:  0.004
    Test::More:     0
    Test::XML:      0.07
    XML::RSS:       1.33
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
